<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 18/08/2017
 * Time: 10:45
 */

namespace backend\controllers;

use backend\rest\controllers\WizdomActiveController;

class FlujosProcesosController extends  WizdomActiveController
{
    public $modelClass = 'backend\models\proceso\flujoProceso\FlujoProceso';


    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }


}