<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 18/08/2017
 * Time: 10:45
 */

namespace backend\controllers;

use yii\rest\ActiveController;

class FlujosProcesosController extends  ActiveController
{
    public $modelClass = 'backend\models\FlujoProceso';


    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }


}