<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 23/01/2018
 * Time: 11:56
 */

namespace backend\rest\controllers;


use yii\base\InvalidConfigException;
use yii\rest\Controller;

class AbstractWizdomPushNotificationsController extends Controller
{
    /**
     * @var string
     */

    protected  $pushNotificationModel;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->pushNotificationModel))
        {
            throw new InvalidConfigException('The "pushNotificationModel" property must be set.');
        }
    }


    protected function verbs()
    {
        return [
            'create' => ['POST'],
        ];
    }


    public function checkAccess(){

    }

    public function actions()
    {
        return [

            'create' => [
                'class' => 'backend\actions\controllers\push\PushAction',
                'modelClass' => $this->pushNotificationModel,
                'checkAccess' => [$this, 'checkAccess']
            ],

        ];
    }

    /**
     * @inheritdoc
     */

}