<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 04/04/2018
 * Time: 16:50
 */
namespace backend\models\idioma\idiomaEmpleado;

use backend\models\empleado\Empleado;
use backend\models\idioma\Idioma;
use backend\models\procesoModelConnector\IProcesoSubject;
use yii\base\ModelEvent;
use yii\db\ActiveRecord;
use backend\models\abstractWizdomModel\AbstractWizdomModel;

class IdiomaEmpleado extends AbstractWizdomModel implements  IProcesoSubject
{
    const EVENT_BEFORE_CONVALIDADO = 'EVENT_BEFORE_CONVALIDADO';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_BEFORE_UPDATE,[$this,"beforeUpdate"]);
    }

    public static function tableName()
    {
        return 'IDIOMA_EMPLEADO';
    }

    public static function primaryKey()
    {
        return ["compania", "codigo_empleado", "idioma"];
    }

    public function getExceptionHandler()
    {

    }

    public function rules()
    {
        return
            [
                [
                    ['compania', 'codigo_empleado', 'idioma'], 'required',
                ],
                [
                    [
                        'compania', 'codigo_empleado', 'idioma', 'conversacion', 'lectura',
                        'escritura', 'nivel_lectura', 'nivel_conversacion', 'nivel_escritura',
                        'tstamp', 'convalidado', 'fecha_convalidacion'
                    ],
                    'string'
                ],


            ];
    }

    public function behaviors()
    {
        return [


            'timestamp' => [
                'class' => 'backend\behaviors\TimestampStringBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['tstamp'],
                ]
            ],
            'fecha_convalidacion' => [
                'class' => 'backend\behaviors\TimestampStringBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['fecha_convalidacion'],
                ]
            ],


        ];

    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getEmpleado()
    {
        return $this->hasOne(Empleado::className(), ["compania" => "compania", "codigo_empleado" => "codigo_empleado"]);

    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getIdioma()
    {
        return $this->hasOne(Idioma::className(), ["idioma", "idioma"]);
    }

    public function getNotificationSubject()
    {
        $empleadoNombre = $this->getEmpleado()->one()->getNombreCompleto();
        $idioma = $this->getIdioma()->one()->getAttribute('nombre_idioma');
        return 'Convalidación de Idioma - ' . mb_convert_case(mb_strtolower($empleadoNombre), MB_CASE_TITLE) . ' - ' . $idioma;
    }

    public function getSubjectProcesoDescription()
    {
        $idioma = $this->getIdioma()->one()->getAttribute('nombre_idioma');
        return 'Convalidación de Idioma - ' . $this->$idioma;
    }

    public function beforeUpdate()
    {
        if($this->convalidado=='A')
        {
            $event = new ModelEvent();
            $this->trigger(self::EVENT_BEFORE_CONVALIDADO,$event);
        }

    }



}