<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 26/01/2018
 * Time: 15:20
 */

namespace backend\utils\email\activeRecord;


use backend\utils\email\IEmailable;
use yii\db\ActiveRecord;

abstract class AbstractActiveRecordEmailSender extends ActiveRecord implements IEmailable
{

    public abstract function  attachEmailSenders();

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->attachEmailSenders();
    }

}