<?php
/**
 * Created by PhpStorm.
 * User: LuisDiego
 * Date: 27/11/2017
 * Time: 11:16
 */

namespace backend\models\security\securityUser;


use backend\models\empleado\Empleado;

class SecurityUser extends AbstractWizdomUser
{

    public static function tableName()
    {
        return "SEC_USERS";
    }

    public static function primaryKey()
    {
        return ["login"];
    }
    public function getEmpleado()
    {
        return $this->hasOne(Empleado::className(),["username"=>"login"]);
    }

    public function extraFields()
    {
        $extraFields =  parent::extraFields(); // TODO: Change the autogenerated stub
        $extraFields[] = 'empleado';
        return $extraFields;
    }

    public function fields()
    {
        return ["login","email"];
    }

    public static function getEmpleadoByUsername($username)
    {
        $empleado = Empleado::findOne(["username"=>$username]);
        return $empleado;
    }


}